defmodule Trex.TrackerList do
  
  def all do
    ["udp://11.rarbg.com/announce",
    "udp://tracker.openbittorrent.com:80/announce",
    "udp://tracker.istole.it:80/announce",
    "udp://tracker.publicbt.com:80/announce",
    "udp://tracker.ccc.de:80/announce",
    "udp://tracker.yify-torrents.com:80/announce",
    "udp://tracker.prq.to/announce",
    "http://tracker.yify-torrents.com/announce",
    "udp://tracker.1337x.org:80/announce",
    "http://exodus.desync.com/announce",
    "http://tracker.coppersurfer.tk:6969/announce",
    "http://tracker.blazing.de/announce",
    "http://9.rarbg.com:2710/announce",
    "http://bt.careland.com.cn:6969/announce",
    "udp://tracker.ex.ua:80/announce",
    "udp://coppersurfer.tk:6969/announce",
    "udp://ipv4.tracker.harry.lu:80/announce",
    "udp://12.rarbg.me:80/announce",
    "udp://9.rarbg.com:2710/announce",
    "http://exodus.desync.com:6969/announce",
    "udp://tracker.istole.it:80/announce",
    "udp://open.demonii.com:1337/announce",
    "udp://tracker.publicbt.com:80/announce",
    "udp://tracker.openbittorrent.com:80/announce",
    "http://tracker.torrenty.org:6969/announce",
    "http://mgtracker.org:2710/announce",
    "http://explodie.org:6969/announce",
    "http://121.14.98.151:9090/announce",
    "http://www.eddie4.nl:6969/announce",
    "http://bt.careland.com.cn:6969/announce",
    "udp://tracker.istole.it:80/announce",
    "udp://tracker.publicbt.com:80/announce",
    "udp://open.demonii.com:1337/announce",
    "udp://9.rarbg.com:2710/announce",
    "udp://9.rarbg.me:2710/announce",
    "udp://tracker.ccc.de:80/announce",
    "udp://10.rarbg.me:80/announce",
    "udp://11.rarbg.me:80/announce",
    "udp://12.rarbg.me:80/announce",
    "udp://tracker.openbittorrent.com/announce"]
  end


end
